[package]
name = "obs-websocket"
description = "OBS WebSocket client library"
categories = ["multimedia"]
keywords = ["obs", "websocket", "streaming"]
readme = "README.md"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = []
websocket = ["dep:obws", "dep:futures-util", "dep:tracing", "tokio/time", "tokio/rt", "tokio/macros"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["sync"] }

futures-util = { version = "0.3", optional = true }
obws = { version = "0.15", features = ["events"], optional = true }
tracing = { version = "0.1", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = "0.3"

[[example]]
name = "stream"
required-features = ["websocket"]
[[example]]
name = "youtube"
required-features = ["websocket"]

[lints]
workspace = true
