#![allow(clippy::crate_in_macro_def)]
#![allow(clippy::disallowed_macros)]
#![allow(clippy::disallowed_methods)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::empty_line_after_doc_comments)]
#![allow(clippy::expect_used)]
#![allow(clippy::implicit_clone)]
#![allow(clippy::manual_let_else)]
#![allow(clippy::map_unwrap_or)]
#![allow(clippy::match_same_arms)]
#![allow(clippy::match_wildcard_for_single_variants)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::multiple_crate_versions)]
#![allow(clippy::must_use_candidate)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::option_if_let_else)]
#![allow(clippy::redundant_else)]
#![allow(clippy::return_self_not_must_use)]
#![allow(clippy::single_match_else)]
#![allow(clippy::too_long_first_doc_paragraph)]
#![allow(clippy::uninlined_format_args)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unnested_or_patterns)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::cloned_instead_of_copied)]
#![allow(clippy::double_ended_iterator_last)]
#![allow(clippy::format_push_string)]
#![allow(clippy::future_not_send)]
#![allow(clippy::ignored_unit_patterns)]
#![allow(clippy::manual_is_multiple_of)]
#![allow(clippy::manual_pattern_char_comparison)]
#![allow(clippy::missing_const_for_fn)]
#![allow(clippy::needless_borrows_for_generic_args)]
#![allow(clippy::redundant_closure_for_method_calls)]
#![allow(clippy::unnecessary_debug_formatting)]
#![allow(clippy::unnecessary_literal_bound)]
#![allow(clippy::use_self)]
#![allow(clippy::needless_continue)]
pub mod engine;
pub mod error;
pub mod llm;
pub mod runtime;
pub mod stages;
pub mod types;
