[package]
name = "animations"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
crossterm = "0.27"

[lints]
workspace = true
