///
/// Resources are keyed by label.  URLs appear as inline comments.
use std::collections::HashMap;

use crate::types::PipelineOutput;

pub fn generate_toml(output: &PipelineOutput) -> String {
	let url_map: HashMap<&str, &str> = output.resources.iter().map(|r| (r.label.as_str(), r.url.as_str())).collect();

	let mut lines: Vec<String> = vec![
		"# Generated by tabsched pipeline".into(),
		format!("# run_id: {}", output.run_id),
		format!("# {} resources  {} edges  {} tracks", output.resources.len(), output.edges.len(), output.tracks.len()),
		format!("# model: {}", output.model),
		String::new(),
		format!("window_size = {}", output.window_size),
		String::new(),
	];

	for track in &output.tracks {
		lines.push("[[track]]".into());
		lines.push(format!("label  = {:?}", track.label));
		if let Some(parent) = &track.parent {
			lines.push(format!("parent = {:?}", parent));
		}
		lines.push(format!("target = {}", track.target));

		if !track.resource_labels.is_empty() {
			lines.push("resources = [".into());
			for label in &track.resource_labels {
				let comment = url_map.get(label.as_str()).map(|u| format!("  # {}", u)).unwrap_or_default();
				lines.push(format!("  {:?},{}", label, comment));
			}
			lines.push("]".into());
		}

		lines.push(String::new());
	}

	lines.join("\n")
}
