//! Renders the route inventory as a TypeScript module, alongside the JSON
//! [`super::inventory::snapshot`] already emits. Added for #266.
//!
//! # Why a second renderer, not a second source of truth
//!
//! Both outputs are views over one [`RouteInventory`] value: `dump-routes`
//! calls [`super::inventory::snapshot`] exactly once per run, then either
//! `serde_json`-serialises the result or hands it to [`render_ts`]. There is
//! no second list of paths anywhere in this crate for the two to disagree
//! about — a route added to `ROUTES` in `inventory.rs` shows up in both
//! artefacts on the next run, or in neither. [`render_ts`] reads
//! `RouteEntry::full_path` rather than recomputing it, for the same reason
//! `full_path` itself exists: so nothing outside `RouteDescriptor::full_path`
//! re-derives the `/api/v1` concatenation and risks getting it wrong.
//!
//! # Why a flag on `dump-routes`, not a second `[[bin]]`
//!
//! A second binary would still depend on `routes::inventory` for the actual
//! data, so it buys no isolation from the first — only a second entry in
//! `Cargo.toml`, a second link step in CI, and a second `--help` a reader has
//! to know exists. A flag keeps one binary and one place to discover both
//! output shapes; see `dump_routes.rs`'s `--ts`.
//!
//! # Why this module carries no schema version
//!
//! See the doc comment on [`super::inventory::INVENTORY_SCHEMA_VERSION`].

use super::inventory::RouteInventory;
use std::collections::BTreeSet;
use std::fmt::Write as _;

/// Kept as a named constant, not inlined, so the doc comment on
/// `dump_routes.rs`'s `--ts` flag and the test below can quote the exact same
/// string rather than two hand-typed copies drifting apart.
const GENERATED_BANNER: &str = "// @generated by `cargo run --bin dump-routes -- --ts`. Do not edit.\n";

/// Renders `inventory` as the `.ts` module #266 asks for: an `API_BASE_PATH`
/// constant plus two path unions, split the same way the router itself
/// splits them — nested under `/api/v1` or not.
///
/// Parameter names (`:id`, `:tab_id`, ...) are not extracted into a separate
/// shape here; #266's own scope note says the client derives them from the
/// literal union with a template-literal type, which keeps this generated
/// file a flat list of strings — reviewable without knowing what a
/// template-literal type is.
#[must_use]
pub fn render_ts(inventory: &RouteInventory) -> String {
	let mut versioned: BTreeSet<&str> = BTreeSet::new();
	let mut unversioned: BTreeSet<&str> = BTreeSet::new();
	for route in &inventory.routes {
		let target = if route.versioned { &mut versioned } else { &mut unversioned };
		target.insert(route.full_path.as_str());
	}

	let mut out = String::new();
	out.push_str(GENERATED_BANNER);
	out.push('\n');
	// `write!` rather than `format!` + `push_str`: `clippy.toml` disallows
	// `format!` (eager allocation), and `write!` avoids the double allocation
	// anyway. Infallible for a `String` target, so the `Result` is discarded.
	let _ = writeln!(out, "export const API_BASE_PATH = \"{}\";\n", inventory.api_base_path);
	out.push_str(&render_union("ServerRoute", None, &versioned));
	out.push('\n');
	out.push_str(&render_union("UnversionedRoute", Some("/** Routes NOT nested under API_BASE_PATH. */"), &unversioned));

	out
}

/// One `export type <name> = ...;` union, alphabetised by [`BTreeSet`] so
/// regenerating without changing a route produces a byte-identical file, the
/// same guarantee [`super::inventory::snapshot`] gives the JSON side.
///
/// `never` is the total completion for an empty category: it is the only
/// TypeScript type with no inhabitants, so it is the correct union of zero
/// string literals rather than an omitted export or a syntax error. Neither
/// category is empty today, but the router owns that fact, not this
/// function.
fn render_union(name: &str, doc: Option<&str>, members: &BTreeSet<&str>) -> String {
	let mut out = String::new();
	if let Some(doc) = doc {
		out.push_str(doc);
		out.push('\n');
	}

	if members.is_empty() {
		let _ = writeln!(out, "export type {name} = never;");
		return out;
	}

	let _ = writeln!(out, "export type {name} =");
	let last = members.len() - 1;
	for (index, member) in members.iter().enumerate() {
		let terminator = if index == last { ";" } else { "" };
		let _ = writeln!(out, "  | \"{member}\"{terminator}");
	}
	out
}

#[cfg(test)]
mod tests {
	use super::{render_ts, GENERATED_BANNER};
	use crate::routes::inventory::{self, RouteDescriptor, ROUTES};
	use regex::Regex;
	use std::collections::BTreeSet;

	fn quoted_literals(block: &str) -> BTreeSet<String> {
		Regex::new(r#""([^"]*)""#).unwrap().captures_iter(block).map(|capture| capture[1].to_owned()).collect()
	}

	fn expected_paths(versioned: bool) -> BTreeSet<String> {
		ROUTES
			.iter()
			.filter(|route: &&RouteDescriptor| route.versioned == versioned)
			.map(RouteDescriptor::full_path)
			.collect()
	}

	/// Slices the rendered module into its two union declarations, so each can
	/// be checked independently without a real TypeScript parser. Starting the
	/// `ServerRoute` slice at its own `export type` line (not at byte 0)
	/// matters: the preceding `API_BASE_PATH` line is itself a quoted string
	/// and would otherwise leak into `quoted_literals`' extraction.
	fn split_unions(rendered: &str) -> (&str, &str) {
		let server_route_start = rendered.find("export type ServerRoute").expect("render_ts always emits a ServerRoute union");
		let unversioned_start = rendered.find("export type UnversionedRoute").expect("render_ts always emits an UnversionedRoute union");
		(&rendered[server_route_start..unversioned_start], &rendered[unversioned_start..])
	}

	/// The load-bearing test #266 asks for: run the emitter, parse its
	/// output, and catch a malformed or wrong union here rather than in the
	/// client's `tsc`. Checked independently against `ROUTES`, not by calling
	/// `render_ts` twice, so a bug inside `render_ts` itself cannot hide.
	#[test]
	fn server_route_union_names_every_versioned_path_exactly_once() {
		let rendered = render_ts(&inventory::snapshot());
		let (server_route_block, _) = split_unions(&rendered);
		assert_eq!(quoted_literals(server_route_block), expected_paths(true));
	}

	#[test]
	fn unversioned_route_union_names_every_unversioned_path_exactly_once() {
		let rendered = render_ts(&inventory::snapshot());
		let (_, unversioned_block) = split_unions(&rendered);
		assert_eq!(quoted_literals(unversioned_block), expected_paths(false));
	}

	#[test]
	fn generated_banner_names_the_exact_command_that_produces_this_file() {
		assert!(render_ts(&inventory::snapshot()).starts_with(GENERATED_BANNER));
	}

	#[test]
	fn api_base_path_constant_matches_the_json_snapshots_field() {
		let snapshot = inventory::snapshot();
		let rendered = render_ts(&snapshot);
		assert!(rendered.contains(&format!("export const API_BASE_PATH = \"{}\";", snapshot.api_base_path)));
	}

	#[test]
	fn rendering_is_deterministic() {
		let snapshot = inventory::snapshot();
		assert_eq!(render_ts(&snapshot), render_ts(&snapshot));
	}
}
