services:
  metabase:
    image: metabase/metabase
    container_name: nfl_db
    ports:
      - "3000:3000"
    volumes:
      - /mnt/storage/users/dev/databases/nfl/metabase-data:/metabase-data
      - /mnt/storage/users/dev/databases/nfl:/data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db

