[package]
name = "nfl_dbs"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
nest = { workspace = true }
serde = { workspace = true }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "sqlite", "uuid", "time"] }

[lints]
workspace = true
