#![allow(clippy::cast_lossless)]
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::cast_precision_loss)]
#![allow(clippy::cast_sign_loss)]
#![allow(clippy::disallowed_macros)]
#![allow(clippy::disallowed_methods)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_glob_use)]
#![allow(clippy::expect_fun_call)]
#![allow(clippy::expect_used)]
#![allow(clippy::future_not_send)]
#![allow(clippy::ignored_unit_patterns)]
#![allow(clippy::implicit_clone)]
#![allow(clippy::items_after_statements)]
#![allow(clippy::large_futures)]
#![allow(clippy::manual_let_else)]
#![allow(clippy::map_unwrap_or)]
#![allow(clippy::match_same_arms)]
#![allow(clippy::match_wildcard_for_single_variants)]
#![allow(clippy::missing_const_for_fn)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::multiple_crate_versions)]
#![allow(clippy::must_use_candidate)]
#![allow(clippy::needless_continue)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::option_if_let_else)]
#![allow(clippy::or_fun_call)]
#![allow(clippy::redundant_clone)]
#![allow(clippy::redundant_pub_crate)]
#![allow(clippy::result_large_err)]
#![allow(clippy::return_self_not_must_use)]
#![allow(clippy::single_match)]
#![allow(clippy::single_match_else)]
#![allow(clippy::should_implement_trait)]
#![allow(clippy::significant_drop_tightening)]
#![allow(clippy::too_long_first_doc_paragraph)]
#![allow(clippy::type_complexity)]
#![allow(clippy::uninlined_format_args)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_async)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::unused_self)]
#![allow(clippy::use_self)]
#![allow(clippy::wildcard_imports)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::derive_partial_eq_without_eq)]
#![allow(clippy::derivable_impls)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::format_push_string)]
#![allow(clippy::needless_borrows_for_generic_args)]
#![allow(clippy::field_reassign_with_default)]
#![allow(clippy::manual_unwrap_or_default)]
#![allow(clippy::explicit_counter_loop)]
#![allow(clippy::significant_drop_in_scrutinee)]
#![allow(clippy::unchecked_time_subtraction)]
#![allow(clippy::if_not_else)]
#![allow(clippy::len_zero)]
#![allow(clippy::manual_string_new)]
mod gdrive;
mod github;
mod gmail;
mod gsheets;
mod util;
// mod ytube;

pub use gdrive::*;
pub use github::*;
pub use gmail::*;
pub use gsheets::*;
pub use util::*;
// pub use ytube::*;
