[package]
name = "chrome_tabs_server"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
chromiumoxide = { version = "0.7.0", features = ["tokio-runtime"] }
dotenv = { workspace = true }
futures = "0.3.31"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "sqlite", "uuid", "time"] }
tokio = { workspace = true, features = ["full"]  }
tower-http = { workspace = true }

# path crates
nest  = { workspace = true }

[lints]
workspace = true
