name: Prepare SQLx
inputs:
  image-name: {required: true}
  needs-sqlx: {required: true}
  needs-migrations: {required: true}
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@v12
    # Cache SQLx CLI binary
    - name: Cache SQLx CLI
      if: inputs.needs-sqlx == 'true'
      id: cache-sqlx
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/sqlx
        key: ${{ runner.os }}-sqlx-cli-0.8-sqlite
    - name: Install SQLx CLI
      if: inputs.needs-sqlx == 'true' && steps.cache-sqlx.outputs.cache-hit != 'true'
      run: |
        nix develop .#ci --command cargo install sqlx-cli \
          --version 0.8 \
          --no-default-features \
          --features sqlite
      shell: bash
    # Run all migrations (auto-discovers all migration folders)
    - name: Run migrations
      if: inputs.needs-migrations == 'true'
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "Running all workspace migrations for ${{ inputs.image-name }}..."

        # Auto-discover and run all migrations in workspace
        sqlx migrate run
      shell: bash
      env:
        DATABASE_URL: sqlite://./dev.db
    # Generate workspace-level .sqlx folder for offline query verification
    - name: Generate SQLx metadata
      if: inputs.needs-sqlx == 'true'
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "Generating workspace-level SQLx metadata..."

        # Generate single workspace .sqlx folder
        sqlx prepare --workspace -- --bin ${{ inputs.image-name }}
      shell: bash
      env:
        DATABASE_URL: sqlite://./dev.db
