name: Prepare SQLx
inputs:
  image-name: {required: true}
  needs-sqlx: {required: true}
  needs-migrations: {required: true}
  migration-paths: {required: false}
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@v12
    # GREEN AXIS: Use the Nix Magic Cache or Actions cache for cargo binaries
    - name: Cache SQLx CLI
      if: inputs.needs-sqlx == 'true'
      id: cache-sqlx
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/sqlx
        key: ${{ runner.os }}-sqlx-cli-sqlite
    - if: inputs.needs-sqlx == 'true' && steps.cache-sqlx.outputs.cache-hit != 'true'
      run: |
        nix develop .#ci --command cargo install sqlx-cli \
          --no-default-features --features sqlite
      shell: bash
    - if: inputs.needs-migrations == 'true'
      run: |
        # Use the cached binary
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "Running migrations for ${{ inputs.image-name }}..."
        # sqlx migrate run --source ${{ inputs.migration-paths }}
      shell: bash
