name: Prepare SQLx
inputs:
  image-name: {required: true}
  needs-sqlx: {required: true}
  needs-migrations: {required: true}
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@v12
    # Cache SQLx CLI binary
    - name: Cache SQLx CLI
      if: inputs.needs-sqlx == 'true'
      id: cache-sqlx
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/sqlx
        key: ${{ runner.os }}-sqlx-cli-sqlite
    # Install SQLx CLI if not cached
    - name: Install SQLx CLI
      if: inputs.needs-sqlx == 'true' && steps.cache-sqlx.outputs.cache-hit != 'true'
      run: |
        nix develop .#ci --command cargo install sqlx-cli \
          --no-default-features \
          --features sqlite
      shell: bash
    # Generate workspace-level .sqlx folder for offline query verification
    - name: Generate SQLx metadata
      if: inputs.needs-sqlx == 'true'
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "Generating workspace-level SQLx metadata..."

        # Generate single workspace .sqlx folder
        sqlx prepare --workspace -- --bin ${{ inputs.image-name }}
      shell: bash
      env:
        DATABASE_URL: sqlite://./dev.db
