services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - '3030:3000'
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - /mnt/storage/users/dev/metabase-data:/metabase-data
      - /mnt/storage/users/dev/databases:/data:ro
    networks:
      - monitoring-network
    mem_limit: 2G
    cpus: 1.5
    pids_limit: 100
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
          pids: 100
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
networks:
  monitoring-network:
    external: true
volumes:
  metabase_data:
    external: true
