networks:
  monitoring-network:
    driver: bridge
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  redis_data:
    driver: local
  redisinsight_data:
    driver: local
  metabase_data:
    driver: local
