services:
  transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcriber
    restart: unless-stopped
    environment:
      # OpenTelemetry
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=transcriber
      # NATS
      - NATS_URL=nats://nats:4222
      # Whisper model settings (CPU-optimized)
      - WHISPER_MODEL=/models/ggml-tiny.en-q5_1.bin
      - WHISPER_THREADS=2 # Use only 2 threads to leave room for other services
      # Buffer settings - increase to reduce transcription frequency
      - BUFFER_DURATION=3 # 3 seconds (vs 2) = less frequent transcriptions
      # Logging
      - RUST_LOG=info,transcriber=info
      # CPU Priority
      - NICE_LEVEL=10 # Lower priority (higher nice = lower priority)
    volumes:
      # Mount external SSD for models
      - ${WHISPER_MODELS_PATH:-/mnt/storage/users/dev/models/whisper-models}:/models:ro
    networks:
      - observability
    depends_on:
      - nats
      - otel-collector
    # CPU and memory limits
    deploy:
      resources:
        limits:
          cpus: '2.0' # Max 2 cores (50% of your 4-core system)
          memory: 1G
        reservations:
          cpus: '0.5' # Guarantee at least 0.5 cores
          memory: 512M
    # CPU scheduling - lower priority, yield to other services
    cpu_shares: 512 # Default is 1024, so this is 50% priority
    # OOM adjustments - kill this first if memory is tight
    oom_score_adj: 500
    healthcheck:
      test: ["CMD", "pgrep", "transcriber"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
