[package]
name = "noobgit"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
notify = { workspace = true }
serde = { workspace = true }


[lints]
workspace = true
