#![allow(clippy::disallowed_macros)]
#![allow(clippy::if_not_else)]
#![allow(clippy::if_same_then_else)]
#![allow(clippy::implicit_clone)]
#![allow(clippy::missing_const_for_fn)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::multiple_crate_versions)]
#![allow(clippy::must_use_candidate)]
#![allow(clippy::needless_return)]
#![allow(clippy::non_std_lazy_statics)]
#![allow(clippy::option_if_let_else)]
#![allow(clippy::redundant_else)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::uninlined_format_args)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unnested_or_patterns)]
#![allow(clippy::derive_partial_eq_without_eq)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::use_self)]
pub mod ast;
pub mod lexer;
pub mod parser;
