name: Docker Build
inputs:
  dockerfile:
    required: true
  image-name:
    required: true
  docker-repo:
    required: true
  push:
    description: "Toggle to actually push to registry"
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3
    # Only login if we are actually pushing (saves network/auth calls)
    - if: inputs.push == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push == 'true' }}
        tags: ${{ inputs.docker-repo }}:latest
        # GREEN AXIS: The magic sauce. 
        # type=gha uses the GitHub Actions cache backend to store Docker layers.
        cache-from: type=gha,scope=${{ inputs.image-name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}
