[package]
name = "tuvitu"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
thiserror = { workspace = true }
termion = "4.0.3"
once_cell = { workspace = true }
regex = { workspace = true }

[lints]
workspace = true
