[package]
name = "splay_diagram"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
wasm-bindgen = "0.2.95"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[lints]
workspace = true
