#![allow(clippy::or_fun_call)]
#![allow(clippy::cast_precision_loss)]
#![allow(clippy::cast_lossless)]
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::derivable_impls)]
#![allow(clippy::derive_partial_eq_without_eq)]
#![allow(clippy::disallowed_macros)]
#![allow(clippy::disallowed_methods)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::ignored_unit_patterns)]
#![allow(clippy::manual_is_multiple_of)]
#![allow(clippy::match_same_arms)]
#![allow(clippy::match_wildcard_for_single_variants)]
#![allow(clippy::missing_const_for_fn)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::must_use_candidate)]
#![allow(clippy::return_self_not_must_use)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::should_implement_trait)]
#![allow(clippy::uninlined_format_args)]
#![allow(clippy::use_self)]
#![allow(clippy::wildcard_imports)]
#![allow(clippy::multiple_crate_versions)]
#![allow(clippy::option_if_let_else)]
#![allow(clippy::single_match)]
#![allow(clippy::single_match_else)]
#![allow(clippy::map_unwrap_or)]
#[cfg(feature = "ws-events")]
pub mod events;

#[cfg(feature = "ws-events")]
pub use events::{unified_event, UnifiedEvent};

#[cfg(feature = "tabsched")]
pub mod tabsched;
